version: '3.9'
services:
  php-apache:
    build:
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - ./php/src:/var/www/html/
    ports:
      - "8000:80"
    depends_on:
      - db
      
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD} # ดึงรหัสผ่านจาก .env สำหรับ root
      MYSQL_DATABASE: ${DB_NAME}          # ตั้งชื่อฐานข้อมูล
    ports:
      - "9906:3306"
      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8888:80"
    restart: always
    environment:
      PMA_HOST: db
